/*!
 * @file
 * @brief Methods to flash the LEDS on the RSK dev Kit
 * File originally generated by Renesas.
 *
 * Copyright (c) 2014 - General Electric - All rights reserved.
 */

#ifndef FLASHLED_H
#define FLASHLED_H

/*!
 * Flash the Rx210 Dev Kit LEDS
 */
void Led_Flash(void);

/*!
 * Toggle the Rx210 Dev Kit LEDS
 */
void Led_Toggle(void);

#endif
