/*!
 * @file
 * @brief Hardware setup for the Rx210 Dev Kit
 * File originally generated by Renesas
 *
 * Copyright (c) 2014 - General Electric - All rights reserved.
 */

#ifndef HWSETUP_H
#define HWSETUP_H

/*!
 * Initialize the Rx210 Dev Kit Hardware
 */
void HardwareSetup(void);

#endif
