/*!
 * @file
 * @brief Methods to control the Timer on the Rx210 Dev board
 * File originally generated by Renesas
 *
 * Copyright (c) 2014 - General Electric - All rights reserved.
 */

#ifndef TIMERADC_H
#define TIMERADC_H

/*!
 * Initialize the Timer Adc Module
 */
void AdcTimer_Init(void);

#endif
