/*!
 * @file
 * @brief Methods to flash the LEDS on the RSK dev Kit
 * File originally generated by Renesas.
 *
 * Copyright (c) 2014 - General Electric - All rights reserved.
 */

#include "r_pdl_io_port.h"
#include "r_pdl_cmt.h"
#include "r_pdl_definitions.h"
#include "Led.h"

extern uint8_t switchFlag;
static uint16_t flashCount = 0xC8;

void CB_TimerLED(void)
{
   Led_Toggle();
   flashCount--;
}

void Led_Flash(void)
{
   bool err = true;

   err &= R_CMT_Create
      (
         0,
         PDL_CMT_PCLK_DIV_512,
         0xFE0,
         CB_TimerLED,
         3
         );

   err &= R_CMT_Destroy
      (
         0
         );

   while(!err)
      ;
}

void Led_Toggle(void)
{
   bool err = true;

   err &= R_IO_PORT_Modify
      (
         PDL_IO_PORT_1_4|PDL_IO_PORT_1_5|PDL_IO_PORT_1_6|\
         PDL_IO_PORT_1_7,
         PDL_IO_PORT_XOR,
         1
         );

   while(!err)
      ;
}
