/*!
 * @file
 * @brief Methods to control the Timer on the Rx210 Dev board
 * File originally generated by Renesas
 *
 * Copyright (c) 2014 - General Electric - All rights reserved.
 */

#ifndef TIMERADC_H
#define TIMERADC_H

void Initialize_Timer_ADC(void);

#endif
