/*!
 * @file
 * @brief Methods to control the Timer on the Rx210 Dev board
 * File originally generated by Renesas
 *
 * Copyright (c) 2014 - General Electric - All rights reserved.
 */

#include "r_pdl_io_port.h"
#include "r_pdl_adc_12.h"
#include "r_pdl_cmt.h"
#include "r_pdl_definitions.h"
#include "AdcTimer.h"
#include "Led.h"

static void StartTimer(void);
static void StartADC(void);
static void CB_ADConversion(void);
static void CB_Timer(void);

uint16_t ad_value[16];

void AdcTimer_Init(void)
{
   StartTimer();
   StartADC();
}

static void StartTimer(void)
{
   bool err = true;

   // Configure compare match timer to call CB_TimerADC to start AD Conversion
   err &= R_CMT_Create
      (
         0,
         PDL_CMT_PCLK_DIV_512,
         0x03FF,
         CB_Timer,
         3
         );

   while(!err)
      ;
}

static void StartADC(void)
{
   bool err = true;

   // Set analog channel AN000
   err &= R_ADC_12_Set
      (
         PDL_ADC_12_PIN_AN000_P40
         );

   // Configure the ADC in single mode, software triggered (one shot operation)
   err &= R_ADC_12_CreateUnit
      (
         0,
         PDL_ADC_12_SCAN_SINGLE,
         PDL_NO_DATA,
         PDL_NO_DATA,
         PDL_NO_DATA,
         PDL_NO_DATA,
         PDL_NO_DATA,
         CB_ADConversion,
         6,
         PDL_NO_FUNC,
         PDL_NO_DATA
         );

   // Configure the ADC channel AN000
   err &= R_ADC_12_CreateChannel
      (
         0,
         0,
         PDL_ADC_12_CH_GROUP_A|\
 PDL_ADC_12_CH_SAMPLE_AND_HOLD_ENABLE,
         5E-6
         );

   // Start the AD conversion
   err &= R_ADC_12_Control
      (
         PDL_ADC_12_0_ON
         );

   while(!err)
      ;
}

static void CB_ADConversion(void)
{
   /* Declare error flag */
   bool err = true;

   // Initialises a temporary copy of 'ad_value' storage variable
   uint16_t ad_value_x16 = 0x0;

   // Fetch ADC value
   err &= R_ADC_12_Read
      (
         0,
         ad_value,
         PDL_NO_PTR
         );

   // Toggle LEDs
   Led_Toggle();

   // Increase clock delay by a factor of 16
   ad_value_x16 = (uint16_t)((ad_value[0] * 0x10));

   // Adjust the minimum value to ensure blink rate is visible
   if(ad_value_x16 < 1800)
   {
      ad_value_x16 = 1800;
   }

   // Start a new timer delay based on ADC value
   err &= R_CMT_Control
      (
         0,
         PDL_CMT_CONSTANT,
         (double )ad_value_x16
         );

   while(!err)
      ;
}

static void CB_Timer(void)
{
   // Declare error flag
   bool err = true;

   // Start A/D conversion
   err &= R_ADC_12_Control
      (
         PDL_ADC_12_0_ON
         );

   while(!err)
      ;
}
