/*!
 * @file
 * @brief Hardware setup for the Rx210 Dev Kit
 * File originally generated by Renesas
 *
 * Copyright (c) 2014 - General Electric - All rights reserved.
 */

#include "r_pdl_io_port.h"
#include "r_pdl_cgc.h"
#include "r_pdl_lpc.h"
#include "r_pdl_definitions.h"
#include "hwsetup.h"
#include "Switch.h"
#include "Rtc.h"

void ConfigureOperatingFrequency(void)
{
   bool err = true;

   //Configure the PLL to use the 20.0 MHz crystal as clock input
   err &= R_CGC_Set
      (
         PDL_CGC_CLK_MAIN,
         PDL_CGC_BCLK_DIV_1 | PDL_CGC_MAIN_RESONATOR,
         20E6,
         20E6,
         20E6,
         20E6,
         20E6,
         PDL_NO_DATA
         );

   /* Configure the clocks as follows -
    Clock Description              Frequency
    ----------------------------------------
    PLL Clock frequency...............100MHz
    System Clock Frequency.............50MHz
    Peripheral Module Clock B..........25MHz
    Peripheral Module Clock D..........50MHz
    FlashIF Clock......................25MHz
    External Bus Clock.................25MHz */

   err &= R_CGC_Set
      (
         PDL_CGC_CLK_PLL,
         PDL_CGC_BCLK_DIV_2,
         100E6,
         50E6,
         50E6,
         25E6,
         25E6,
         25E6
         );

   // Allow 100us for the main clock to stabilize
   err &= R_CMT_CreateOneShot
      (
         0,
         PDL_NO_DATA,
         100E-6,
         PDL_NO_FUNC,
         0
         );

   // Change to high-speed operating mode
   err &= R_LPC_Control(
      PDL_LPC_CHANGE_HIGH_SPEED
      );

   // Select the PLL as the clock source
   err &= R_CGC_Control
      (
         PDL_CGC_CLK_PLL,
         PDL_CGC_SUB_CLOCK_CL_STANDARD,
         PDL_CGC_SUB_CLOCK_ENABLE
         );

   while(!err)
      ;
}

void ConfigureOutputPorts(void)
{
   bool err = true;

   // Configure the LED pins (LED0-LED3) as outputs
   err &= R_IO_PORT_Set
      (
         PDL_IO_PORT_1_4|PDL_IO_PORT_1_5|PDL_IO_PORT_1_6|PDL_IO_PORT_1_7,
         PDL_IO_PORT_OUTPUT
         );

   // Set LED pin outputs as high (all LEDs off)
   err &= R_IO_PORT_Write
      (
         PDL_IO_PORT_1_4|PDL_IO_PORT_1_5|PDL_IO_PORT_1_6|PDL_IO_PORT_1_7,
         1
         );

   // Configure the debug LCD data pins (DLCD7-DLCD4) as outputs
   err &= R_IO_PORT_Set
      (
         PDL_IO_PORT_H_0|PDL_IO_PORT_H_1|PDL_IO_PORT_H_2|
         PDL_IO_PORT_H_3,
         PDL_IO_PORT_OUTPUT
         );

   // Set debug LCD data pin (DLCD7-DLCD4) outputs as low
   err &= R_IO_PORT_Write
      (
         PDL_IO_PORT_H_0|PDL_IO_PORT_H_1|PDL_IO_PORT_H_2|
         PDL_IO_PORT_H_3,
         0
         );

   // Configure the debug LCD control pin (DLCDRS) and enable pin (DLCDE) as output
   err &= R_IO_PORT_Set
      (
         PDL_IO_PORT_J_1|PDL_IO_PORT_J_3,
         PDL_IO_PORT_OUTPUT
         );

   // Set the debug LCD control pin (DLCDRS) and enable pin (DLCDE) as output low
   err &= R_IO_PORT_Write
      (
         PDL_IO_PORT_J_1|PDL_IO_PORT_J_3,
         0
         );

   while(!err)
      ;
}

void HardwareSetup(void)
{
   ConfigureOperatingFrequency();
   ConfigureOutputPorts();
   Switch_Init();
   Rtc_Init();
}
